apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cartservice
  annotations:
    github.com/project-slug: arnavrazdann/cartservice
    backstage.io/techdocs-ref: value
  links:
    - url: https://github.com/arnavrazdann
      title: My github
spec:
  type: other
  lifecycle: unknown
  owner: innov
