apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cartservice
  annotations:
    github.com/project-slug: arnavrazdann/cartservice
    backstage.io/techdocs-ref: value
spec:
  type: other
  lifecycle: unknown
  owner: innov
